# schedule jobs to test services
push: 
  - name: "bbc"
    url: "http://bbc.com"
  - name: "baidu" 
    url: "http://baidu.com"
  - name: "bing" 
    url: "http://bing.com"
  - name: "youku" 
    url: "http://youku.com"
  - name: "58" 
    url: "http://58.com"

